
wallaby:
  debug: true
  env:
    kind: electron

  workers:
    initial: 1
    regular: 1

  webpack:
    entryPatterns:
      - scripts/entry.js
      - scripts/*_test.coffee

    node:
      __dirname: true
      __filename: true

    module:
      loaders:
      - test: !!js/regexp /\.(yaml|json)$/
        loaders:
          - json-loader
      - test: !!js/regexp /\.html$/
        loaders:
          - raw-loader

  files:
    # Test libs
    - pattern: node_modules/chai/chai.js
      instrument: false
    - pattern: node_modules/sinon/pkg/sinon.js
      instrument: false

    # entry.js has to be loaded in advance (and pre-processed by webpack).
    - pattern: "scripts/entry.js"

    # App and Tests
    - pattern: scripts/*.js
      load: false
    - pattern: scripts/*.coffee
      load: false

    - pattern: "scripts/*.js"
      load: false

    - pattern: "scripts/**/*_test.coffee"
      ignore: true

  tests:
    - pattern: "scripts/**/*_test.coffee"
      load: false
